import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { CypressTestGeneratorGeneratedModule, cypresstestgeneratorGeneratedSharedModule } from './generated/module.js';
import { CypressTestGeneratorValidator, registerValidationChecks } from './cypress-test-generator-validator.js';
import { CypressTestGeneratorCompletionProvider } from './cypress-test-generator-completion.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type CypressTestGeneratorAddedServices = {
    validation: {
        CypressTestGeneratorValidator: CypressTestGeneratorValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type CypressTestGeneratorServices = LangiumServices & CypressTestGeneratorAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const CypressTestGeneratorModule: Module<CypressTestGeneratorServices, PartialLangiumServices & CypressTestGeneratorAddedServices> = {
    validation: {
        CypressTestGeneratorValidator: () => new CypressTestGeneratorValidator()
    },
    lsp: {
        CompletionProvider: services => new CypressTestGeneratorCompletionProvider(services)
        }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createCypressTestGeneratorServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    CypressTestGenerator: CypressTestGeneratorServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        cypresstestgeneratorGeneratedSharedModule
    );
    const CypressTestGenerator = inject(
        createDefaultModule({ shared }),
        CypressTestGeneratorGeneratedModule,
        CypressTestGeneratorModule
    );
    shared.ServiceRegistry.register(CypressTestGenerator);
    registerValidationChecks(CypressTestGenerator);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, CypressTestGenerator };
}
